/**
 * ⚠️  DO NOT EDIT THE GENERATED game.js FILE! ⚠️
 * 
 * This TypeScript file (game.ts) is the source of truth.
 * The game.js file is automatically generated by TypeScript compiler.
 * 
 * To make changes:
 * 1. Edit this file (game.ts)
 * 2. Run: npm run build (or npm run dev for watch mode)
 * 3. The game.js file will be automatically updated
 */

// Data model interfaces
interface Player {
    name: string;
    score: number;
}

interface PlayerRoundData {
    playerName: string;
    bid: number;
    actual: number;
    bonus: number;
    roundScore: number;
}

interface RoundData {
    roundNumber: number;
    playerData: PlayerRoundData[];
}

interface GameStateData {
    players: Player[];
    rounds: RoundData[];
    currentRound: number;
}

// Google Analytics gtag function declaration
declare function gtag(...args: any[]): void;

// PWA Install Prompt Interface
interface BeforeInstallPromptEvent extends Event {
    prompt(): Promise<void>;
    userChoice: Promise<{ outcome: 'accepted' | 'dismissed'; platform: string }>;
}

/**
 * GameState - Handles data persistence and storage
 * Pure data layer that only manages localStorage operations
 */
class GameState {
    private readonly storageKey = 'skullKingGameState';

    load(): GameStateData | null {
        const saved = localStorage.getItem(this.storageKey);
        return saved ? JSON.parse(saved) : null;
    }

    save(state: GameStateData): void {
        localStorage.setItem(this.storageKey, JSON.stringify(state));
    }

    clear(): void {
        localStorage.removeItem(this.storageKey);
    }

    getDefaultState(): GameStateData {
        return {
            players: [],
            rounds: [],
            currentRound: 1
        };
    }
}

/**
 * GameViewModel - Contains all business logic and state management
 * Manages game rules, scoring calculations, validation, and analytics
 */
class GameViewModel {
    private gameState: GameState;
    private state: GameStateData;
    private tempPlayers: string[] = [];
    private modalConfirmCallback: (() => void) | null = null;

    constructor() {
        this.gameState = new GameState();
        this.state = this.gameState.load() || this.gameState.getDefaultState();
    }

    // State Management
    getGameState(): GameStateData {
        return { ...this.state };
    }

    saveState(): void {
        this.gameState.save(this.state);
    }

    clearState(): void {
        this.gameState.clear();
        this.state = this.gameState.getDefaultState();
    }

    // Player Management
    getTempPlayers(): string[] {
        return [...this.tempPlayers];
    }

    initializeTempPlayers(): void {
        this.tempPlayers = this.state.players.map(p => p.name);
        if (this.tempPlayers.length === 0) {
            this.tempPlayers = [''];
        }
    }

    updateTempPlayer(index: number, value: string): void {
        this.tempPlayers[index] = value;
    }

    addTempPlayer(): void {
        this.tempPlayers.push('');
    }

    removeTempPlayer(index: number): void {
        if (this.tempPlayers.length > 1) {
            this.tempPlayers.splice(index, 1);
        } else {
            this.tempPlayers[0] = '';
        }
    }

    setTempPlayers(players: string[]): void {
        this.tempPlayers = [...players];
    }

    validateAndStartGame(): string | null {
        const validNames = this.tempPlayers.filter(name => name.trim() !== '');
        
        if (validNames.length < 2) {
            return 'Ye need at least 2 pirates to sail these waters!';
        }

        if (validNames.length > 8) {
            return 'Too many pirates! Maximum 8 scallywags allowed.';
        }

        // Check for duplicate names
        const uniqueNames = new Set(validNames.map(name => name.trim().toLowerCase()));
        if (uniqueNames.size !== validNames.length) {
            return 'Each pirate needs a unique name, ye scurvy dogs!';
        }

        // Initialize game state
        this.state.players = validNames.map(name => ({ name: name.trim(), score: 0 }));
        this.state.rounds = [];
        this.state.currentRound = 1;
        this.saveState();

        // Track analytics
        this.trackEvent('game_start', {
            event_category: 'game',
            event_label: 'new_game', 
            player_count: this.state.players.length,
            value: this.state.players.length
        });

        return null; // Success
    }

    // Scoring Logic
    private calculateRoundScore(bid: number, actual: number, bonus: number, roundNumber: number): number {
        if (bid === 0) {
            // Zero bid scoring
            return actual === 0 ? 10 * roundNumber + bonus : -10 * roundNumber;
        } else {
            // Non-zero bid scoring
            if (bid === actual) {
                // Correct prediction: 20 points per trick + bonus
                return 20 * actual + bonus;
            } else {
                // Incorrect prediction: -10 points per difference (no bonus)
                return -10 * Math.abs(bid - actual);
            }
        }
    }

    // Round Management
    getCurrentRoundNumber(): number {
        return this.state.currentRound;
    }
    
    // Card distribution logic for Skull King (70 card deck)
    getCardsPerRound(roundNumber: number, playerCount: number): number {
        // Skull King is a 10-round game - rounds beyond 10 are invalid
        if (roundNumber > 10) {
            throw new Error(`Invalid round number: ${roundNumber}. Skull King only has 10 rounds.`);
        }
        
        // Basic validation
        if (roundNumber < 1) {
            throw new Error(`Invalid round number: ${roundNumber}. Round number must be 1 or greater.`);
        }
        
        if (playerCount < 1) {
            throw new Error(`Invalid player count: ${playerCount}. Must have at least 1 player.`);
        }
        
        const totalCards = 70;
        const idealCards = roundNumber;
        const cardsNeeded = idealCards * playerCount;
        
        // If we can deal the ideal number of cards, do so
        if (cardsNeeded <= totalCards) {
            return idealCards;
        }
        
        // Otherwise, calculate the maximum cards we can deal per player
        return Math.floor(totalCards / playerCount);
    }
    
    // Get maximum tricks available for current round
    getMaxTricksForCurrentRound(): number {
        return this.getCardsPerRound(this.state.currentRound, this.state.players.length);
    }

    validateRoundData(data: { [playerName: string]: { bid: number; actual: number; bonus: number } }, roundNumber?: number): string | null {
        const targetRound = roundNumber || this.state.currentRound;
        
        for (const [playerName, playerData] of Object.entries(data)) {
            const { bid, actual, bonus } = playerData;

            // Check for invalid numbers (NaN)
            if (isNaN(bid) || isNaN(actual) || isNaN(bonus)) {
                return `Invalid number entered for ${playerName}. Please enter valid numbers only.`;
            }

            // Integer validation (check first)
            if (!Number.isInteger(bid) || !Number.isInteger(actual) || !Number.isInteger(bonus)) {
                return `All values must be whole numbers for ${playerName}.`;
            }

            // Basic validation
            if (bid < 0 || actual < 0) {
                return `Bid and actual tricks must be non-negative for ${playerName}.`;
            }

            // Round-specific validation: bids and actual tricks can't exceed available cards
            const maxTricks = this.getCardsPerRound(targetRound, this.state.players.length);
            if (bid > maxTricks) {
                return `${playerName}'s bid (${bid}) can't exceed ${maxTricks} tricks in round ${targetRound} with ${this.state.players.length} players.`;
            }
            if (actual > maxTricks) {
                return `${playerName} can't win more than ${maxTricks} tricks in round ${targetRound} with ${this.state.players.length} players. Actual: ${actual}`;
            }

            // Bonus point validation - only applies when correctly predicting tricks
            if (bid !== actual && bonus > 0) {
                return `${playerName} can only earn bonus points when correctly predicting tricks! (Bid: ${bid}, Actual: ${actual})`;
            }

            // Reasonable bonus limits
            if (Math.abs(bonus) > 100) {
                return `${playerName}'s bonus points seem unreasonable (${bonus}). Please check your entry.`;
            }
        }

        // Validate that total actual wins equals the number of tricks available
        const maxTricks = this.getCardsPerRound(targetRound, this.state.players.length);
        const totalActualWins = Object.values(data).reduce((sum, playerData) => sum + playerData.actual, 0);
        
        if (totalActualWins !== maxTricks) {
            return `Total tricks won (${totalActualWins}) must equal the number of tricks available (${maxTricks}) in round ${targetRound} with ${this.state.players.length} players.`;
        }

        return null; // Valid
    }

    addRound(data: { [playerName: string]: { bid: number; actual: number; bonus: number } }): string | null {
        const validationError = this.validateRoundData(data);
        if (validationError) {
            return validationError;
        }

        const roundData: RoundData = {
            roundNumber: this.state.currentRound,
            playerData: []
        };

        // Process each player's data
        for (const player of this.state.players) {
            const playerRoundData = data[player.name];
            const roundScore = this.calculateRoundScore(
                playerRoundData.bid,
                playerRoundData.actual,
                playerRoundData.bonus,
                this.state.currentRound
            );

            roundData.playerData.push({
                playerName: player.name,
                bid: playerRoundData.bid,
                actual: playerRoundData.actual,
                bonus: playerRoundData.bonus,
                roundScore
            });

            // Update player's total score
            player.score += roundScore;
        }

        this.state.rounds.push(roundData);
        this.state.currentRound++;
        this.saveState();

        // Track analytics
        this.trackEvent('round_complete', {
            event_category: 'gameplay',
            event_label: 'round_finished',
            round_number: roundData.roundNumber,
            player_count: this.state.players.length,
            value: roundData.roundNumber
        });

        return null; // Success
    }

    removeLastRound(): { [playerName: string]: { bid: number; actual: number; bonus: number } } | null {
        if (this.state.rounds.length === 0) {
            return null;
        }

        const lastRound = this.state.rounds.pop()!;
        
        // Revert scores from the removed round
        for (const playerData of lastRound.playerData) {
            const player = this.state.players.find(p => p.name === playerData.playerName);
            if (player) {
                player.score -= playerData.roundScore;
            }
        }

        // Decrease current round number
        this.state.currentRound = Math.max(1, this.state.currentRound - 1);
        this.saveState();

        // Track analytics
        this.trackEvent('round_removed', {
            event_category: 'gameplay',
            event_label: 'round_deleted',
            round_number: lastRound.roundNumber,
            value: lastRound.roundNumber
        });

        // Return the round data for pre-filling inputs
        const result: { [playerName: string]: { bid: number; actual: number; bonus: number } } = {};
        for (const playerData of lastRound.playerData) {
            result[playerData.playerName] = {
                bid: playerData.bid,
                actual: playerData.actual,
                bonus: playerData.bonus
            };
        }

        return result;
    }


    // Modal Management
    setModalConfirmCallback(callback: (() => void) | null): void {
        this.modalConfirmCallback = callback;
    }

    executeModalConfirm(): void {
        if (this.modalConfirmCallback) {
            this.modalConfirmCallback();
            this.modalConfirmCallback = null;
        }
    }

    // New Game Logic
    startNewGame(keepNames: boolean): void {
        const existingNames = keepNames ? this.state.players.map(p => p.name) : [];
        
        this.clearState();
        
        if (existingNames.length > 0) {
            this.tempPlayers = [...existingNames];
        } else {
            this.tempPlayers = [''];
        }

        // Track analytics
        this.trackEvent('new_game_started', {
            event_category: 'navigation',
            event_label: keepNames ? 'same_players' : 'new_players',
            kept_names: keepNames,
            player_count: existingNames.length,
            value: existingNames.length
        });
    }

    // Analytics
    private trackEvent(eventName: string, parameters: { [key: string]: any } = {}): void {
        console.log('🔍 Analytics Event:', eventName, parameters);
        
        if (typeof gtag !== 'undefined') {
            gtag('event', eventName, parameters);
            console.log('✅ Event sent to Google Analytics');
        } else {
            console.warn('⚠️ gtag not available - analytics event not sent');
        }
    }

    // Game Status
    isGameActive(): boolean {
        return this.state.players.length > 0;
    }

    isGameComplete(): boolean {
        return this.state.currentRound > 10;
    }

    hasRounds(): boolean {
        return this.state.rounds.length > 0;
    }

    getPlayerCount(): number {
        return this.state.players.length;
    }

    getRoundCount(): number {
        return this.state.rounds.length;
    }

    // Commentary generation
    generateCommentary(): string {
        if (this.state.rounds.length === 0) {
            return '';
        }

        const lastRound = this.state.rounds[this.state.rounds.length - 1];
        const perfectPlayers = lastRound.playerData.filter(p => p.bid === p.actual);
        const disasters = lastRound.playerData.filter(p => Math.abs(p.bid - p.actual) >= 3);
        const bigScores = lastRound.playerData.filter(p => p.roundScore >= 40);

        // Perfect round (everyone got their bid)
        if (perfectPlayers.length === this.state.players.length) {
            const comments = [
                "Blimey! Every scallywag nailed their bid! The sea gods smile upon ye all!",
                "Shiver me timbers! Perfect round for all hands! Not a single miscalculation!",
                "Avast! Every pirate sailed true to their word! What sorcery be this?"
            ];
            return comments[Math.floor(Math.random() * comments.length)];
        }

        // Single disaster
        if (disasters.length === 1) {
            const player = disasters[0];
            const comments = [
                `Avast! ${player.playerName} be sinkin' faster than a ship with no hull!`,
                `${player.playerName} just sailed straight into a kraken! What a disaster!`,
                `Blimey! ${player.playerName} be drownin' in their own overconfidence!`
            ];
            return comments[Math.floor(Math.random() * comments.length)];
        }

        // Multiple big scores
        if (bigScores.length >= 2) {
            const comments = [
                "Pieces of eight! Multiple pirates be strikin' gold this round!",
                "Shiver me timbers! Several captains just filled their treasure chests!",
                "Multiple pirates be countin' serious doubloons after that performance!"
            ];
            return comments[Math.floor(Math.random() * comments.length)];
        }

        // Default commentary
        const defaultComments = [
            "Another round in the books! The seas be unpredictable as always!",
            "The tide turns with each round! Stay sharp, ye scurvy dogs!",
            "Mixed fortunes this round! The ocean gives and takes as she pleases!"
        ];
        return defaultComments[Math.floor(Math.random() * defaultComments.length)];
    }

    // Winner determination
    getWinner(): Player[] | null {
        if (this.state.players.length === 0) return null;
        
        const sortedPlayers = [...this.state.players].sort((a, b) => b.score - a.score);
        const highestScore = sortedPlayers[0].score;
        
        // Return all players with the highest score (in case of tie)
        return sortedPlayers.filter(player => player.score === highestScore);
    }
    
    generateWinnerAnnouncement(): string {
        const winners = this.getWinner();
        if (!winners || winners.length === 0) {
            return "The seas have claimed all! No winners this voyage!";
        }
        
        if (winners.length === 1) {
            const winner = winners[0];
            const winnerMessages = [
                `Huzzah! Captain ${winner.name} emerges victorious with ${winner.score} pieces of eight! The crown of Skull King belongs to ye!`,
                `Avast! ${winner.name} has conquered the seven seas with ${winner.score} doubloons! All hail the new Skull King!`,
                `Shiver me timbers! ${winner.name} stands triumphant with ${winner.score} gold coins! Ye be the true master of these waters!`,
                `Blimey! ${winner.name} has plundered the most treasure with ${winner.score} pieces of eight! The Skull King's throne is yours!`
            ];
            return winnerMessages[Math.floor(Math.random() * winnerMessages.length)];
        } else {
            // Multiple winners (tie)
            const winnerNames = winners.map(w => w.name).join(' and ');
            const score = winners[0].score;
            const tieMessages = [
                `Avast! We have a tie! ${winnerNames} both finish with ${score} pieces of eight! Ye must share the Skull King's crown!`,
                `Blimey! ${winnerNames} have tied with ${score} doubloons each! Two captains, one throne - may the best pirate win!`,
                `Shiver me timbers! ${winnerNames} are deadlocked at ${score} gold coins! The seas couldn't choose between such worthy pirates!`
            ];
            return tieMessages[Math.floor(Math.random() * tieMessages.length)];
        }
    }

    // Text-to-Speech
    createScoreAnnouncement(): string {
        if (this.state.players.length === 0) {
            return "No active game to announce, ye landlubber!";
        }

        let announcement = "Ahoy mateys! ";

        // Add the pirate commentary from the last round first if available
        const commentary = this.generateCommentary();
        if (commentary) {
            announcement += `${commentary} `;
        }

        const sortedPlayers = [...this.state.players].sort((a, b) => b.score - a.score);
        
        announcement += `Now for the current bounty after round ${this.state.rounds.length}... `;
        
        sortedPlayers.forEach((player, index) => {
            if (index === 0) {
                announcement += `Leading the fleet, we have ${player.name} with ${player.score} pieces of eight! `;
            } else if (index === sortedPlayers.length - 1 && sortedPlayers.length > 2) {
                announcement += `And bringing up the rear, ${player.name} with ${player.score} doubloons. `;
            } else {
                announcement += `${player.name} follows with ${player.score} gold coins. `;
            }
        });

        announcement += "May the winds favor the worthy! Arrr!";
        return announcement;
    }

    // Public method for testing
    testCalculateRoundScore(bid: number, actual: number, bonus: number, roundNumber: number): number {
        return this.calculateRoundScore(bid, actual, bonus, roundNumber);
    }
}

/**
 * SkullKingGame - Main game controller using MVVM architecture
 * Coordinates between ViewModel (business logic) and DOM (view)
 */
class SkullKingGame {
    private viewModel: GameViewModel;
    private deferredPrompt: BeforeInstallPromptEvent | null = null;

    constructor() {
        this.viewModel = new GameViewModel();
        this.init();
    }

    private init(): void {
        this.setupEventListeners();
        this.initializePWA();
        this.updateUI();
    }

    private setupEventListeners(): void {
        // Landing page
        const newGameBtn = document.getElementById('new-game-btn');
        newGameBtn?.addEventListener('click', () => this.handleNewGame());

        // Player names setup
        const addPlayerBtn = document.getElementById('add-player-btn');
        addPlayerBtn?.addEventListener('click', () => this.handleAddPlayer());

        const startGameBtn = document.getElementById('start-game-btn');
        startGameBtn?.addEventListener('click', () => this.handleStartGame());

        const cancelSetupBtn = document.getElementById('cancel-setup-btn');
        cancelSetupBtn?.addEventListener('click', () => this.showLanding());

        // In-game
        const newGameIngameBtn = document.getElementById('new-game-ingame-btn');
        newGameIngameBtn?.addEventListener('click', () => this.confirmNewGame());

        const addRoundBtn = document.getElementById('add-round-btn');
        addRoundBtn?.addEventListener('click', () => this.handleAddRound());

        const readScoresBtn = document.getElementById('read-scores-btn');
        readScoresBtn?.addEventListener('click', () => this.readScores());

        // Modal
        const modalConfirm = document.getElementById('modal-confirm');
        modalConfirm?.addEventListener('click', () => this.handleModalConfirm());

        const modalCancel = document.getElementById('modal-cancel');
        modalCancel?.addEventListener('click', () => this.hideModal());

        // New Game Modal Options
        const samePlayersBtn = document.getElementById('same-players-btn');
        samePlayersBtn?.addEventListener('click', () => this.handleSamePlayersNewGame());

        const newPlayersBtn = document.getElementById('new-players-btn');
        newPlayersBtn?.addEventListener('click', () => this.handleNewPlayersNewGame());

        const cancelNewGameBtn = document.getElementById('cancel-new-game-btn');
        cancelNewGameBtn?.addEventListener('click', () => this.hideModal());
    }

    // Event Handlers
    private handleNewGame(): void {
        if (this.viewModel.isGameActive()) {
            this.confirmNewGame();
        } else {
            this.startPlayerSetup();
        }
    }

    private handleAddPlayer(): void {
        const tempPlayers = this.viewModel.getTempPlayers();
        if (tempPlayers.length >= 8) {
            this.showError('Maximum 8 pirates allowed! Can\'t add more players.');
            return;
        }
        this.viewModel.addTempPlayer();
        this.updatePlayerInputs();
    }

    private handleStartGame(): void {
        const error = this.viewModel.validateAndStartGame();
        if (error) {
            this.showError(error);
            return;
        }
        this.updateUI();
    }

    private handleAddRound(): void {
        const gameState = this.viewModel.getGameState();
        const roundData = this.collectRoundData(gameState.players);
        
        const error = this.viewModel.addRound(roundData);
        
        if (error) {
            this.showError(error);
            return;
        }

        this.updateUI();
        this.clearRoundInputs();
        this.showCommentary();
    }

    private handleModalConfirm(): void {
        this.viewModel.executeModalConfirm();
        this.hideModal();
    }

    private handleSamePlayersNewGame(): void {
        this.viewModel.startNewGame(true); // Keep names
        this.hideModal();
        
        // If we have valid players from keeping names, start the game immediately
        const tempPlayers = this.viewModel.getTempPlayers();
        const validNames = tempPlayers.filter(name => name.trim() !== '');
        if (validNames.length >= 2) {
            const error = this.viewModel.validateAndStartGame();
            if (!error) {
                this.updateUI();
                return;
            }
        }
        
        // Otherwise, go to player setup
        this.startPlayerSetup();
    }

    private handleNewPlayersNewGame(): void {
        this.viewModel.startNewGame(false); // Don't keep names
        this.hideModal();
        this.startPlayerSetup();
    }

    // Helper Methods
    private startPlayerSetup(): void {
        this.viewModel.initializeTempPlayers();
        this.showPlayerSetup();
        this.updatePlayerInputs();
    }

    private confirmNewGame(): void {
        const gameState = this.viewModel.getGameState();
        const playerNames = gameState.players.map(p => p.name).join(', ');
        
        this.showNewGameModal(
            'Start New Game',
            'Choose how ye want to start yer new adventure:',
            playerNames
        );
    }

    // View Methods
    private updateUI(): void {
        const gameState = this.viewModel.getGameState();
        
        if (gameState.players.length === 0) {
            this.showLanding();
        } else {
            this.showGame();
            this.updateScoreDisplay(gameState.players);
            
            // Check if game is complete
            const isGameComplete = this.viewModel.isGameComplete();
            if (isGameComplete) {
                this.showWinnerAnnouncement();
                this.hideNewRoundInputs();
            } else {
                this.hideWinnerAnnouncement();
                this.showNewRoundInputs();
                this.updateRoundInputs(gameState.players, gameState.currentRound);
            }
            
            this.updatePreviousRounds(gameState.rounds);
        }
    }

    private showLanding(): void {
        document.getElementById('landing-section')?.classList.remove('hidden');
        document.getElementById('player-names-section')?.classList.add('hidden');
        document.getElementById('game-section')?.classList.add('hidden');
        document.getElementById('new-game-section')?.classList.add('hidden');
    }

    private showPlayerSetup(): void {
        document.getElementById('landing-section')?.classList.add('hidden');
        document.getElementById('player-names-section')?.classList.remove('hidden');
        document.getElementById('game-section')?.classList.add('hidden');
        document.getElementById('new-game-section')?.classList.add('hidden');
    }

    private showGame(): void {
        document.getElementById('landing-section')?.classList.add('hidden');
        document.getElementById('player-names-section')?.classList.add('hidden');
        document.getElementById('game-section')?.classList.remove('hidden');
        document.getElementById('new-game-section')?.classList.remove('hidden');
    }

    private updatePlayerInputs(): void {
        const container = document.getElementById('player-names-inputs');
        const addPlayerBtn = document.getElementById('add-player-btn');
        if (!container) return;

        const tempPlayers = this.viewModel.getTempPlayers();
        container.innerHTML = tempPlayers.map((name, index) => `
            <div class="player-name-input">
                <input type="text" id="player-${index}" placeholder="Enter pirate name..." value="${name}" onchange="game.updateTempPlayer(${index}, this.value)">
                <button class="btn-remove" onclick="game.removePlayer(${index})" title="Remove player">✕</button>
            </div>
        `).join('');

        // Hide/show Add Pirate button based on player count (max 8)
        if (addPlayerBtn) {
            if (tempPlayers.length >= 8) {
                addPlayerBtn.style.display = 'none';
            } else {
                addPlayerBtn.style.display = 'inline-block';
            }
        }
    }

    private updateScoreDisplay(players: Player[]): void {
        const scoreDisplay = document.getElementById('score-display');
        if (!scoreDisplay) return;

        scoreDisplay.innerHTML = players.map(player => `
            <div class="player-score">
                <h4>${player.name}</h4>
                <div class="score-value">${player.score}</div>
            </div>
        `).join('');
    }

    private updateRoundInputs(players: Player[], currentRound: number): void {
        const container = document.getElementById('round-inputs');
        const roundNumberEl = document.getElementById('round-number');
        
        if (!container) return;
        
        const maxTricks = this.viewModel.getMaxTricksForCurrentRound();
        const roundDisplay = maxTricks < currentRound ? 
            `${currentRound} (${maxTricks} cards each)` : 
            currentRound.toString();
            
        if (roundNumberEl) {
            roundNumberEl.textContent = roundDisplay;
        }

        container.innerHTML = players.map(player => `
            <div class="player-round-input">
                <h4>${player.name}</h4>
                <div class="round-input-row">
                    <div class="input-group">
                        <label for="bid-${player.name}" class="input-label">Bid</label>
                        <input type="number" id="bid-${player.name}" placeholder="0" min="0" max="${maxTricks}">
                    </div>
                    <div class="input-group">
                        <label for="actual-${player.name}" class="input-label">Won</label>
                        <input type="number" id="actual-${player.name}" placeholder="0" min="0" max="${maxTricks}">
                    </div>
                    <div class="input-group">
                        <label for="bonus-${player.name}" class="input-label">Bonus</label>
                        <input type="number" id="bonus-${player.name}" placeholder="0" min="0">
                    </div>
                </div>
            </div>
        `).join('');
    }

    private updatePreviousRounds(rounds: RoundData[]): void {
        const container = document.getElementById('previous-rounds');
        if (!container) return;

        if (rounds.length === 0) {
            container.innerHTML = '';
            return;
        }

        // Display rounds in reverse order (newest first)
        const sortedRounds = [...rounds].reverse();
        
        container.innerHTML = sortedRounds.map((round, index) => `
            <div class="round-display parchment">
                <div class="round-header">
                    <h3>Round ${round.roundNumber}</h3>
                    ${index === 0 ? '<button class="btn btn-secondary" onclick="game.handleUpdateLastRound()">Edit Round</button>' : ''}
                </div>
                <div class="round-data">
                    ${round.playerData.map(data => `
                        <div class="player-round-data">
                            <strong>${data.playerName}</strong>
                            <span>Bid: ${data.bid}</span>
                            <span>Won: ${data.actual}</span>
                            <span>Bonus: ${data.bonus}</span>
                            <span>Score: ${data.roundScore > 0 ? '+' : ''}${data.roundScore}</span>
                        </div>
                    `).join('')}
                </div>
            </div>
        `).join('');
    }

    private collectRoundData(players: Player[]): { [playerName: string]: { bid: number; actual: number; bonus: number } } {
        const data: { [playerName: string]: { bid: number; actual: number; bonus: number } } = {};

        for (const player of players) {
            const bidInput = document.getElementById(`bid-${player.name}`) as HTMLInputElement;
            const actualInput = document.getElementById(`actual-${player.name}`) as HTMLInputElement;
            const bonusInput = document.getElementById(`bonus-${player.name}`) as HTMLInputElement;

            // Parse values, defaulting to 0 for empty inputs
            const bidValue = bidInput?.value?.trim() || '0';
            const actualValue = actualInput?.value?.trim() || '0';
            const bonusValue = bonusInput?.value?.trim() || '0';

            data[player.name] = {
                bid: parseInt(bidValue),
                actual: parseInt(actualValue),
                bonus: parseInt(bonusValue)
            };
        }

        return data;
    }

    private clearRoundInputs(): void {
        const inputs = document.querySelectorAll('#round-inputs input') as NodeListOf<HTMLInputElement>;
        inputs.forEach(input => input.value = '');
    }

    private showCommentary(): void {
        const commentary = this.viewModel.generateCommentary();
        const commentaryEl = document.getElementById('pirate-commentary');
        const textEl = document.getElementById('commentary-text');

        if (commentaryEl && textEl && commentary) {
            textEl.textContent = commentary;
            commentaryEl.classList.remove('hidden');
        }
    }
    
    private showWinnerAnnouncement(): void {
        const winnerAnnouncement = document.getElementById('winner-announcement');
        const winnerText = document.getElementById('winner-text');
        if (winnerAnnouncement && winnerText) {
            const announcement = this.viewModel.generateWinnerAnnouncement();
            winnerText.textContent = announcement;
            winnerAnnouncement.classList.remove('hidden');
        }
    }
    
    private hideWinnerAnnouncement(): void {
        const winnerAnnouncement = document.getElementById('winner-announcement');
        if (winnerAnnouncement) {
            winnerAnnouncement.classList.add('hidden');
        }
    }
    
    private showNewRoundInputs(): void {
        const newRoundEl = document.getElementById('new-round');
        if (newRoundEl) {
            newRoundEl.classList.remove('hidden');
        }
    }
    
    private hideNewRoundInputs(): void {
        const newRoundEl = document.getElementById('new-round');
        if (newRoundEl) {
            newRoundEl.classList.add('hidden');
        }
    }

    private showNewGameModal(title: string, message: string, playerNames: string): void {
        const modal = document.getElementById('modal');
        const titleEl = document.getElementById('modal-title');
        const messageEl = document.getElementById('modal-message');
        const checkboxContainer = document.getElementById('modal-checkbox-container');
        const modalButtons = document.getElementById('modal-buttons');
        const modalOptions = document.getElementById('modal-options');
        const newGameOptions = document.getElementById('new-game-options');
        const samePlayersBtn = document.getElementById('same-players-btn');

        if (!modal || !titleEl || !messageEl) return;

        titleEl.textContent = title;
        messageEl.textContent = message;

        // Hide standard options
        checkboxContainer?.classList.add('hidden');
        modalOptions?.classList.add('hidden');
        modalButtons?.classList.add('hidden');
        
        // Show new game options
        newGameOptions?.classList.remove('hidden');
        
        // Update same players button text
        if (samePlayersBtn) {
            samePlayersBtn.textContent = `Same Players (${playerNames})`;
        }

        modal.classList.remove('hidden');
    }

    private showModal(title: string, message: string, showCheckbox: boolean = false): void {
        const modal = document.getElementById('modal');
        const titleEl = document.getElementById('modal-title');
        const messageEl = document.getElementById('modal-message');
        const checkboxContainer = document.getElementById('modal-checkbox-container');
        const modalButtons = document.getElementById('modal-buttons');
        const modalOptions = document.getElementById('modal-options');
        const newGameOptions = document.getElementById('new-game-options');

        if (!modal || !titleEl || !messageEl) return;

        titleEl.textContent = title;
        messageEl.textContent = message;

        // Hide all optional sections by default
        checkboxContainer?.classList.add('hidden');
        modalOptions?.classList.add('hidden');
        newGameOptions?.classList.add('hidden');
        
        // Show standard buttons
        modalButtons?.classList.remove('hidden');

        if (showCheckbox && checkboxContainer) {
            checkboxContainer.classList.remove('hidden');
        }

        modal.classList.remove('hidden');
    }

    private showErrorModal(message: string): void {
        const modal = document.getElementById('modal');
        const titleEl = document.getElementById('modal-title');
        const messageEl = document.getElementById('modal-message');
        const checkboxContainer = document.getElementById('modal-checkbox-container');
        const modalButtons = document.getElementById('modal-buttons');
        const modalOptions = document.getElementById('modal-options');
        const newGameOptions = document.getElementById('new-game-options');
        const modalConfirm = document.getElementById('modal-confirm');
        const modalCancel = document.getElementById('modal-cancel');

        if (!modal || !titleEl || !messageEl) return;

        titleEl.textContent = 'Arr! Input Error';
        messageEl.textContent = message;

        // Hide all optional sections
        checkboxContainer?.classList.add('hidden');
        modalOptions?.classList.add('hidden');
        newGameOptions?.classList.add('hidden');
        modalButtons?.classList.remove('hidden');

        // Show only the confirm button (OK)
        if (modalConfirm && modalCancel) {
            modalConfirm.textContent = 'Aye, I\'ll fix it!';
            modalCancel.style.display = 'none';
        }

        // Clear any existing callback and set error modal behavior
        this.viewModel.setModalConfirmCallback(() => {
            if (modalCancel) modalCancel.style.display = 'inline-block';
            if (modalConfirm) modalConfirm.textContent = 'Aye';
        });

        modal.classList.remove('hidden');
    }

    private hideModal(): void {
        const modal = document.getElementById('modal');
        modal?.classList.add('hidden');
    }

    private getKeepNamesCheckbox(): boolean {
        const checkbox = document.getElementById('keep-names-checkbox') as HTMLInputElement;
        return checkbox?.checked || false;
    }

    private showError(message: string): void {
        this.showErrorModal(message);
    }

    private readScores(): void {
        // Check if browser supports speech synthesis
        if (!('speechSynthesis' in window) || !('SpeechSynthesisUtterance' in window)) {
            this.showErrorModal('Arr! Yer browser doesn\'t support speech. Try a newer vessel!');
            return;
        }

        // Cancel any ongoing speech
        window.speechSynthesis.cancel();

        const announcement = this.viewModel.createScoreAnnouncement();

        // Create and configure the utterance for maximum pirate effect
        const utterance = new SpeechSynthesisUtterance(announcement);
        utterance.rate = 0.7; // Slower and more dramatic
        utterance.pitch = 0.7; // Lower pitch for gruff pirate voice
        utterance.volume = 1;

        // Try to find the most pirate-sounding voice
        const voices = window.speechSynthesis.getVoices();
        const pirateVoice = voices.find(voice => 
            voice.lang.startsWith('en') && 
            (voice.name.toLowerCase().includes('male') ||
             voice.name.toLowerCase().includes('daniel'))
        ) || voices.find(voice => voice.lang.startsWith('en'));

        if (pirateVoice) {
            utterance.voice = pirateVoice;
        }

        // Speak!
        window.speechSynthesis.speak(utterance);
    }

    // Public API for HTML event handlers
    public updateTempPlayer(index: number, value: string): void {
        this.viewModel.updateTempPlayer(index, value);
    }

    public removePlayer(index: number): void {
        this.viewModel.removeTempPlayer(index);
        this.updatePlayerInputs();
    }

    public handleUpdateLastRound(): void {
        // Remove the last round and get its data for pre-filling
        const lastRoundData = this.viewModel.removeLastRound();
        if (!lastRoundData) {
            this.showError('No rounds to edit!');
            return;
        }

        // Ensure the round inputs are visible for editing, even if game was complete
        this.showNewRoundInputs();
        
        // Update UI to reflect the new game state (with last round removed)
        this.updateUI();

        // Populate the inputs with the removed round's data for editing
        for (const [playerName, data] of Object.entries(lastRoundData)) {
            const bidInput = document.getElementById(`bid-${playerName}`) as HTMLInputElement;
            const actualInput = document.getElementById(`actual-${playerName}`) as HTMLInputElement;
            const bonusInput = document.getElementById(`bonus-${playerName}`) as HTMLInputElement;

            if (bidInput) bidInput.value = data.bid.toString();
            if (actualInput) actualInput.value = data.actual.toString();
            if (bonusInput) bonusInput.value = data.bonus.toString();
        }
    }

    // PWA Install Functionality
    private initializePWA(): void {
        // Guard for test environment
        if (typeof document === 'undefined') return;
        
        // Don't show install buttons if already in standalone mode (installed)
        if ((window.matchMedia && window.matchMedia('(display-mode: standalone)').matches) || 
            (window.navigator as any).standalone) {
            this.hideInstallButtons();
            return;
        }
        
        // Add event listeners to existing install buttons
        this.setupInstallButtons();
    }

    private setupInstallButtons(): void {
        // Add event listeners to the mobile install buttons
        const installBtn = document.getElementById('install-app-btn');
        const installBtnLanding = document.getElementById('install-app-btn-landing');
        
        if (installBtn) {
            installBtn.addEventListener('click', () => this.showInstallInstructions());
        }
        
        if (installBtnLanding) {
            installBtnLanding.addEventListener('click', () => this.showInstallInstructions());
        }
    }

    private hideInstallButtons(): void {
        const installBtn = document.getElementById('install-app-btn');
        const installBtnLanding = document.getElementById('install-app-btn-landing');
        
        if (installBtn) {
            installBtn.style.display = 'none';
        }
        
        if (installBtnLanding) {
            installBtnLanding.style.display = 'none';
        }
    }

    private showInstallInstructions(): void {
        // Show instructions for manual installation
        let modal = document.getElementById('install-instructions-modal');
        if (!modal) {
            modal = document.createElement('div');
            modal.id = 'install-instructions-modal';
            modal.className = 'install-modal';
            modal.innerHTML = `
                <div class="install-modal-content">
                    <h3>📱 Add to Home Screen</h3>
                    <div class="install-instructions">
                        <p><strong>For Android Chrome:</strong></p>
                        <ol>
                            <li>Tap the menu (⋮) in browser</li>
                            <li>Select "Add to Home screen"</li>
                            <li>Tap "Add" to confirm</li>
                        </ol>
                        <p><strong>For iOS Safari:</strong></p>
                        <ol>
                            <li>Tap the share button (⎘)</li>
                            <li>Scroll down and tap "Add to Home Screen"</li>
                            <li>Tap "Add" to confirm</li>
                        </ol>
                    </div>
                    <button class="install-modal-close" onclick="this.parentElement.parentElement.style.display='none'">✕ Close</button>
                </div>
            `;
            document.body.appendChild(modal);
        }
        modal.style.display = 'flex';
    }

    // Public method for testing the scoring logic
    public testCalculateRoundScore(bid: number, actual: number, bonus: number, roundNumber: number): number {
        return this.viewModel.testCalculateRoundScore(bid, actual, bonus, roundNumber);
    }
}

// Initialize game
const game = new SkullKingGame();

// Expose class for testing
(window as any).SkullKingGame = SkullKingGame;