/**
 * ⚠️  DO NOT EDIT THE GENERATED game.js FILE! ⚠️
 * 
 * This TypeScript file (game.ts) is the source of truth.
 * The game.js file is automatically generated by TypeScript compiler.
 * 
 * To make changes:
 * 1. Edit this file (game.ts)
 * 2. Run: npm run build (or npm run dev for watch mode)
 * 3. The game.js file will be automatically updated
 */

// Translations will be included in the same file after compilation

// Data model interfaces
type ScoringMode = 'normal' | 'rascal';

interface Player {
    name: string;
    score: number;
}

interface PlayerRoundData {
    playerName: string;
    bid: number;
    actual: number;
    bonus: number;
    roundScore: number;
}

interface RoundData {
    roundNumber: number;
    playerData: PlayerRoundData[];
    commentary: string;
    commentaryMeta?: {
        type: 'perfect' | 'disaster' | 'big_scores' | 'default' | 'start';
        index: number;
        playerName?: string;
    };
}

interface GameStateData {
    players: Player[];
    rounds: RoundData[];
    currentRound: number;
    scoringMode: ScoringMode;
}

// Google Analytics gtag function declaration
declare function gtag(...args: any[]): void;

// PWA Install Prompt Interface
interface BeforeInstallPromptEvent extends Event {
    prompt(): Promise<void>;
    userChoice: Promise<{ outcome: 'accepted' | 'dismissed' }>;
}

// Translation system class
class GameTranslationSystem {
    private currentLanguage: string = 'en';
    private translations: { [key: string]: Translation } = { 
        en: enTranslation, 
        de: deTranslation, 
        es: esTranslation 
    };
    
    constructor() {
        // Try to get saved language from localStorage
        const saved = localStorage.getItem('skull-king-language');
        if (saved && this.translations[saved]) {
            this.currentLanguage = saved;
        } else {
            // Auto-detect browser language
            const browserLang = navigator.language.substr(0, 2);
            if (this.translations[browserLang]) {
                this.currentLanguage = browserLang;
            }
        }
    }
    
    getCurrentLanguage(): string {
        return this.currentLanguage;
    }
    
    setLanguage(lang: string): void {
        if (this.translations[lang]) {
            this.currentLanguage = lang;
            localStorage.setItem('skull-king-language', lang);
            // Trigger update event
            window.dispatchEvent(new CustomEvent('languageChanged', { detail: lang }));
        }
    }
    
    translate(key: keyof Translation, params?: { [key: string]: string | number }): string {
        const translation = this.translations[this.currentLanguage];
        if (!translation || !translation[key]) {
            console.warn(`Translation missing for key: ${key} in language: ${this.currentLanguage}`);
            return this.translations['en'][key] || key;
        }
        
        let result = translation[key];
        
        // Replace parameters if provided
        if (params) {
            Object.entries(params).forEach(([param, value]) => {
                result = result.replace(new RegExp(`\\{${param}\\}`, 'g'), value.toString());
            });
        }
        
        return result;
    }
}

// Global translation system instance
const translationSystem = new GameTranslationSystem();

// Create backward-compatible global i18n object
const i18n = translationSystem;

// Make it available globally for browser environment
if (typeof window !== 'undefined') {
    (window as any).i18n = i18n;
} else if (typeof global !== 'undefined') {
    (global as any).i18n = i18n;
}

/**
 * GameState - Handles data persistence and storage
 * Pure data layer that only manages localStorage operations
 */
class GameState {
    private readonly storageKey = 'skullKingGameState';

    load(): GameStateData | null {
        const saved = localStorage.getItem(this.storageKey);
        return saved ? JSON.parse(saved) : null;
    }

    save(state: GameStateData): void {
        localStorage.setItem(this.storageKey, JSON.stringify(state));
    }

    clear(): void {
        localStorage.removeItem(this.storageKey);
    }

    getDefaultState(): GameStateData {
        return {
            players: [],
            rounds: [],
            currentRound: 1,
            scoringMode: 'normal'
        };
    }
}

/**
 * GameViewModel - Contains all business logic and state management
 * Manages game rules, scoring calculations, validation, and analytics
 */
class GameViewModel {
    private gameState: GameState;
    private state: GameStateData;
    private tempPlayers: string[] = [];
    private modalConfirmCallback: (() => void) | null = null;

    constructor() {
        this.gameState = new GameState();
        this.state = this.gameState.load() || this.gameState.getDefaultState();
    }

    // State Management
    getGameState(): GameStateData {
        return { ...this.state };
    }

    saveState(): void {
        this.gameState.save(this.state);
    }

    clearState(): void {
        this.gameState.clear();
        this.state = this.gameState.getDefaultState();
    }

    // Scoring Mode Management
    getScoringMode(): ScoringMode {
        // First check if there's a saved preference
        const savedPreference = localStorage.getItem('skull-king-scoring-mode') as ScoringMode;
        if (savedPreference && ['normal', 'rascal'].includes(savedPreference)) {
            return savedPreference;
        }
        // Otherwise use the game state or default
        return this.state.scoringMode || 'normal';
    }

    setScoringMode(mode: ScoringMode): void {
        this.state.scoringMode = mode;
        this.saveState();
        // Also save as a separate preference
        localStorage.setItem('skull-king-scoring-mode', mode);
    }

    // Player Management
    getTempPlayers(): string[] {
        return [...this.tempPlayers];
    }

    initializeTempPlayers(): void {
        this.tempPlayers = this.state.players.map(p => p.name);
        if (this.tempPlayers.length === 0) {
            this.tempPlayers = [''];
        }
    }

    updateTempPlayer(index: number, value: string): void {
        this.tempPlayers[index] = value;
    }

    addTempPlayer(): void {
        this.tempPlayers.push('');
    }

    removeTempPlayer(index: number): void {
        if (this.tempPlayers.length > 1) {
            this.tempPlayers.splice(index, 1);
        } else {
            this.tempPlayers[0] = '';
        }
    }

    setTempPlayers(players: string[]): void {
        this.tempPlayers = [...players];
    }

    validateAndStartGame(): string | null {
        const validNames = this.tempPlayers.filter(name => name.trim() !== '');
        
        if (validNames.length < 2) {
            return this.t('min_players_error');
        }

        if (validNames.length > 8) {
            return this.t('max_players_error');
        }

        // Check for duplicate names
        const uniqueNames = new Set(validNames.map(name => name.trim().toLowerCase()));
        if (uniqueNames.size !== validNames.length) {
            return this.t('duplicate_names_error');
        }

        // Initialize game state
        this.state.players = validNames.map(name => ({ name: name.trim(), score: 0 }));
        this.state.rounds = [];
        this.state.currentRound = 1;
        this.saveState();

        // Track analytics
        this.trackEvent('game_start', {
            event_category: 'game',
            event_label: 'new_game', 
            player_count: this.state.players.length,
            value: this.state.players.length
        });

        return null; // Success
    }

    // Scoring Logic
    private calculateRoundScore(bid: number, actual: number, bonus: number, roundNumber: number): number {
        const scoringMode = this.getScoringMode();
        const cardsDealt = this.getCardsPerRound(roundNumber, this.state.players.length);
        
        if (scoringMode === 'rascal') {
            // Rascal's scoring: potential points = 10 × cards dealt
            const potentialPoints = 10 * cardsDealt;
            const difference = Math.abs(bid - actual);
            
            if (difference === 0) {
                // Direct hit: full points + bonus
                return potentialPoints + bonus;
            } else if (difference === 1) {
                // Glancing blow: half points + half bonus
                return Math.floor(potentialPoints / 2) + Math.floor(bonus / 2);
            } else {
                // Complete miss: no points
                return 0;
            }
        } else {
            // Normal/Traditional Skull King scoring
            if (bid === 0) {
                // Zero bid scoring: 10 points per card dealt for success
                return actual === 0 ? 10 * cardsDealt + bonus : -10 * cardsDealt;
            } else {
                // Non-zero bid scoring
                if (bid === actual) {
                    // Correct prediction: 20 points per card dealt + bonus
                    return 20 * cardsDealt + bonus;
                } else {
                    // Incorrect prediction: -10 points per difference (no bonus)
                    return -10 * Math.abs(bid - actual);
                }
            }
        }
    }

    // Input Validation
    validateSinglePlayerInput(bid: number, actual: number, bonus: number, playerName: string, roundNumber?: number): string | null {
        const targetRound = roundNumber || this.state.currentRound;
        
        // Check for invalid numbers (NaN)
        if (isNaN(bid) || isNaN(actual) || isNaN(bonus)) {
            return this.t('invalid_number_error', { playerName });
        }

        // Integer validation
        if (!Number.isInteger(bid) || !Number.isInteger(actual) || !Number.isInteger(bonus)) {
            return this.t('whole_numbers_error', { playerName });
        }

        // Basic validation
        if (bid < 0 || actual < 0 || bonus < 0) {
            return this.t('non_negative_error', { playerName });
        }

        // Round-specific validation: bids and actual tricks can't exceed available cards
        const maxTricks = this.getCardsPerRound(targetRound, this.state.players.length);
        if (bid > maxTricks) {
            return this.t('bid_exceeds_tricks_error', {
                playerName,
                bid: bid.toString(),
                maxTricks: maxTricks.toString(),
                round: targetRound.toString(),
                playerCount: this.state.players.length.toString()
            });
        }
        if (actual > maxTricks) {
            return this.t('actual_exceeds_tricks_error', {
                playerName,
                maxTricks: maxTricks.toString(),
                round: targetRound.toString(),
                playerCount: this.state.players.length.toString(),
                actual: actual.toString()
            });
        }

        // Bonus point validation - only applies when correctly predicting tricks
        if (bid !== actual && bonus > 0) {
            return this.t('bonus_without_correct_bid_error', {
                playerName,
                bid: bid.toString(),
                actual: actual.toString()
            });
        }

        // Reasonable bonus limits
        if (Math.abs(bonus) > 100) {
            return this.t('unreasonable_bonus_error', {
                playerName,
                bonus: bonus.toString()
            });
        }

        return null; // Valid
    }

    // Round Management
    getCurrentRoundNumber(): number {
        return this.state.currentRound;
    }
    
    // Card distribution logic for Skull King (70 card deck)
    getCardsPerRound(roundNumber: number, playerCount: number): number {
        // Skull King is a 10-round game - rounds beyond 10 are invalid
        if (roundNumber > 10) {
            throw new Error(`Invalid round number: ${roundNumber}. Skull King only has 10 rounds.`);
        }
        
        // Basic validation
        if (roundNumber < 1) {
            throw new Error(`Invalid round number: ${roundNumber}. Round number must be 1 or greater.`);
        }
        
        if (playerCount < 1) {
            throw new Error(`Invalid player count: ${playerCount}. Must have at least 1 player.`);
        }
        
        const totalCards = 70;
        const idealCards = roundNumber;
        const cardsNeeded = idealCards * playerCount;
        
        // If we can deal the ideal number of cards, do so
        if (cardsNeeded <= totalCards) {
            return idealCards;
        }
        
        // Otherwise, calculate the maximum cards we can deal per player
        return Math.floor(totalCards / playerCount);
    }
    
    // Get maximum tricks available for current round
    getMaxTricksForCurrentRound(): number {
        return this.getCardsPerRound(this.state.currentRound, this.state.players.length);
    }

    validateRoundData(data: { [playerName: string]: { bid: number; actual: number; bonus: number } }, roundNumber?: number): string | null {
        const targetRound = roundNumber || this.state.currentRound;
        
        // Validate each player's input
        for (const [playerName, playerData] of Object.entries(data)) {
            const { bid, actual, bonus } = playerData;
            const validationError = this.validateSinglePlayerInput(bid, actual, bonus, playerName, targetRound);
            if (validationError) {
                return validationError;
            }
        }

        // Validate that total actual wins equals the number of tricks available
        const maxTricks = this.getCardsPerRound(targetRound, this.state.players.length);
        const totalActualWins = Object.values(data).reduce((sum, playerData) => sum + playerData.actual, 0);
        
        if (totalActualWins !== maxTricks) {
            return this.t('total_tricks_mismatch_error', {
                totalActual: totalActualWins.toString(),
                maxTricks: maxTricks.toString(),
                round: targetRound.toString(),
                playerCount: this.state.players.length.toString()
            });
        }

        return null; // Valid
    }

    addRound(data: { [playerName: string]: { bid: number; actual: number; bonus: number } }): string | null {
        const validationError = this.validateRoundData(data);
        if (validationError) {
            return validationError;
        }

        const roundData: RoundData = {
            roundNumber: this.state.currentRound,
            playerData: [],
            commentary: ''
        };

        // Process each player's data
        for (const player of this.state.players) {
            const playerRoundData = data[player.name];
            const roundScore = this.calculateRoundScore(
                playerRoundData.bid,
                playerRoundData.actual,
                playerRoundData.bonus,
                this.state.currentRound
            );

            roundData.playerData.push({
                playerName: player.name,
                bid: playerRoundData.bid,
                actual: playerRoundData.actual,
                bonus: playerRoundData.bonus,
                roundScore
            });

            // Update player's total score
            player.score += roundScore;
        }

        // Generate commentary for this round
        roundData.commentary = this.generateRoundCommentary(roundData);

        this.state.rounds.push(roundData);
        this.state.currentRound++;
        this.saveState();

        // Track analytics
        this.trackEvent('round_complete', {
            event_category: 'gameplay',
            event_label: 'round_finished',
            round_number: roundData.roundNumber,
            player_count: this.state.players.length,
            value: roundData.roundNumber
        });

        // Check if game is complete and track it
        if (this.isGameComplete()) {
            const sortedPlayers = this.getPlayersSortedByScore();
            const winner = sortedPlayers[0];
            
            this.trackEvent('game_completed', {
                event_category: 'gameplay',
                event_label: 'game_finished',
                winning_score: winner.score,
                scoring_mode: this.getScoringMode(),
                language: translationSystem.getCurrentLanguage(),
                value: this.state.players.length
            });
        }

        return null; // Success
    }

    removeLastRound(): { [playerName: string]: { bid: number; actual: number; bonus: number } } | null {
        if (this.state.rounds.length === 0) {
            return null;
        }

        const lastRound = this.state.rounds.pop()!;
        
        // Revert scores from the removed round
        for (const playerData of lastRound.playerData) {
            const player = this.state.players.find(p => p.name === playerData.playerName);
            if (player) {
                player.score -= playerData.roundScore;
            }
        }

        // Decrease current round number
        this.state.currentRound = Math.max(1, this.state.currentRound - 1);
        this.saveState();

        // Track analytics
        this.trackEvent('round_removed', {
            event_category: 'gameplay',
            event_label: 'round_deleted',
            round_number: lastRound.roundNumber,
            value: lastRound.roundNumber
        });

        // Return the round data for pre-filling inputs
        const result: { [playerName: string]: { bid: number; actual: number; bonus: number } } = {};
        for (const playerData of lastRound.playerData) {
            result[playerData.playerName] = {
                bid: playerData.bid,
                actual: playerData.actual,
                bonus: playerData.bonus
            };
        }

        return result;
    }


    // Modal Management
    setModalConfirmCallback(callback: (() => void) | null): void {
        this.modalConfirmCallback = callback;
    }

    executeModalConfirm(): void {
        if (this.modalConfirmCallback) {
            this.modalConfirmCallback();
            this.modalConfirmCallback = null;
        }
    }

    // New Game Logic
    startNewGame(keepNames: boolean): void {
        const existingNames = keepNames ? this.state.players.map(p => p.name) : [];
        
        // Preserve the scoring mode preference before clearing state
        const currentScoringMode = this.getScoringMode();
        
        this.clearState();
        
        // Restore the scoring mode preference after clearing state
        this.setScoringMode(currentScoringMode);
        
        if (existingNames.length > 0) {
            this.tempPlayers = [...existingNames];
        } else {
            this.tempPlayers = [''];
        }

        // Track analytics
        this.trackEvent('new_game_started', {
            event_category: 'navigation',
            event_label: keepNames ? 'same_players' : 'new_players',
            kept_names: keepNames,
            player_count: existingNames.length,
            value: existingNames.length
        });
    }

    // Analytics
    private trackEvent(eventName: string, parameters: { [key: string]: any } = {}): void {
        console.log('🔍 Analytics Event:', eventName, parameters);
        
        if (typeof gtag !== 'undefined') {
            gtag('event', eventName, parameters);
            console.log('✅ Event sent to Google Analytics');
        } else {
            console.warn('⚠️ gtag not available - analytics event not sent');
        }
    }

    // Game Status
    isGameActive(): boolean {
        return this.state.players.length > 0;
    }

    isGameComplete(): boolean {
        return this.state.currentRound > 10;
    }

    hasRounds(): boolean {
        return this.state.rounds.length > 0;
    }

    getPlayerCount(): number {
        return this.state.players.length;
    }

    getRoundCount(): number {
        return this.state.rounds.length;
    }

    // Get players sorted by score (highest first)
    getPlayersSortedByScore(): Player[] {
        return [...this.state.players].sort((a, b) => b.score - a.score);
    }

    getPlayers(): Player[] {
        return [...this.state.players];
    }

    // Commentary generation for a specific round
    generateRoundCommentary(roundData: RoundData): string {
        const perfectPlayers = roundData.playerData.filter(p => p.bid === p.actual);
        const disasters = roundData.playerData.filter(p => Math.abs(p.bid - p.actual) >= 3);
        const bigScores = roundData.playerData.filter(p => p.roundScore >= 40);

        let commentaryMeta: any = {};

        // Perfect round (everyone got their bid)
        if (perfectPlayers.length === this.state.players.length) {
            const index = Math.floor(Math.random() * 3);
            commentaryMeta = { type: 'perfect', index };
            const comments = [
                this.t('perfect_round_1'),
                this.t('perfect_round_2'),
                this.t('perfect_round_3')
            ];
            roundData.commentaryMeta = commentaryMeta;
            return comments[index];
        }

        // Single disaster
        if (disasters.length === 1) {
            const player = disasters[0];
            const index = Math.floor(Math.random() * 3);
            commentaryMeta = { type: 'disaster', index, playerName: player.playerName };
            const comments = [
                this.t('disaster_1', { playerName: player.playerName }),
                this.t('disaster_2', { playerName: player.playerName }),
                this.t('disaster_3', { playerName: player.playerName })
            ];
            roundData.commentaryMeta = commentaryMeta;
            return comments[index];
        }

        // Multiple big scores
        if (bigScores.length >= 2) {
            const index = Math.floor(Math.random() * 3);
            commentaryMeta = { type: 'big_scores', index };
            const comments = [
                this.t('big_scores_1'),
                this.t('big_scores_2'),
                this.t('big_scores_3')
            ];
            roundData.commentaryMeta = commentaryMeta;
            return comments[index];
        }

        // Default commentary - always return something
        const index = Math.floor(Math.random() * 5);
        commentaryMeta = { type: 'default', index };
        const defaultComments = [
            this.t('default_1'),
            this.t('default_2'),
            this.t('default_3'),
            this.t('default_4'),
            this.t('default_5')
        ];
        roundData.commentaryMeta = commentaryMeta;
        return defaultComments[index];
    }

    // Regenerate commentary from metadata (for language changes)
    regenerateCommentaryFromMeta(meta: any): string {
        if (!meta) return this.t('default_1');

        switch (meta.type) {
            case 'perfect':
                const perfectComments = [
                    this.t('perfect_round_1'),
                    this.t('perfect_round_2'),
                    this.t('perfect_round_3')
                ];
                return perfectComments[meta.index] || perfectComments[0];
            
            case 'disaster':
                const disasterComments = [
                    this.t('disaster_1', { playerName: meta.playerName }),
                    this.t('disaster_2', { playerName: meta.playerName }),
                    this.t('disaster_3', { playerName: meta.playerName })
                ];
                return disasterComments[meta.index] || disasterComments[0];
            
            case 'big_scores':
                const bigScoreComments = [
                    this.t('big_scores_1'),
                    this.t('big_scores_2'),
                    this.t('big_scores_3')
                ];
                return bigScoreComments[meta.index] || bigScoreComments[0];
            
            case 'start':
                const startComments = [
                    this.t('start_1'),
                    this.t('start_2'),
                    this.t('start_3')
                ];
                return startComments[meta.index] || startComments[0];
            
            case 'default':
            default:
                const defaultComments = [
                    this.t('default_1'),
                    this.t('default_2'),
                    this.t('default_3'),
                    this.t('default_4'),
                    this.t('default_5')
                ];
                return defaultComments[meta.index] || defaultComments[0];
        }
    }

    // Get commentary for current state (for voice reading)
    getCurrentCommentary(): string {
        if (this.state.rounds.length === 0) {
            const startComments = [
                this.t('start_1'),
                this.t('start_2'),
                this.t('start_3')
            ];
            return startComments[Math.floor(Math.random() * startComments.length)];
        }

        // Return the commentary from the most recent round, regenerated in current language
        const lastRound = this.state.rounds[this.state.rounds.length - 1];
        if (lastRound.commentaryMeta) {
            const regeneratedCommentary = this.regenerateCommentaryFromMeta(lastRound.commentaryMeta);
            // Update the stored commentary text to match current language
            lastRound.commentary = regeneratedCommentary;
            return regeneratedCommentary;
        }
        return lastRound.commentary; // Fallback to stored text for backwards compatibility
    }

    // Update all round commentaries to current language
    updateAllCommentariesToCurrentLanguage(): void {
        this.state.rounds.forEach(round => {
            if (round.commentaryMeta) {
                round.commentary = this.regenerateCommentaryFromMeta(round.commentaryMeta);
            }
        });
    }

    // Winner determination
    getWinner(): Player[] | null {
        if (this.state.players.length === 0) return null;
        
        const sortedPlayers = [...this.state.players].sort((a, b) => b.score - a.score);
        const highestScore = sortedPlayers[0].score;
        
        // Return all players with the highest score (in case of tie)
        return sortedPlayers.filter(player => player.score === highestScore);
    }
    
    generateWinnerAnnouncement(): string {
        const winners = this.getWinner();
        if (!winners || winners.length === 0) {
            return "The seas have claimed all! No winners this voyage!";
        }
        
        if (winners.length === 1) {
            const winner = winners[0];
            const winnerMessages = [
                this.t('winner_single_1', { name: winner.name, score: winner.score.toString() }),
                this.t('winner_single_2', { name: winner.name, score: winner.score.toString() }),
                this.t('winner_single_3', { name: winner.name, score: winner.score.toString() }),
                this.t('winner_single_4', { name: winner.name, score: winner.score.toString() })
            ];
            return winnerMessages[Math.floor(Math.random() * winnerMessages.length)];
        } else {
            // Multiple winners (tie)
            const winnerNames = winners.map(w => w.name).join(' and ');
            const score = winners[0].score;
            const tieMessages = [
                this.t('winner_tie_1', { names: winnerNames, score: score.toString() }),
                this.t('winner_tie_2', { names: winnerNames, score: score.toString() }),
                this.t('winner_tie_3', { names: winnerNames, score: score.toString() })
            ];
            return tieMessages[Math.floor(Math.random() * tieMessages.length)];
        }
    }

    // Text-to-Speech
    createScoreAnnouncement(): string {
        if (this.state.players.length === 0) {
            return this.t('no_game_announce');
        }

        let announcement = this.t('ahoy_mateys');

        // Always use the current commentary from the viewmodel
        const commentary = this.getCurrentCommentary();
        announcement += `${commentary} `;

        const sortedPlayers = [...this.state.players].sort((a, b) => b.score - a.score);
        
        announcement += this.t('current_bounty_after', { rounds: this.state.rounds.length.toString() });
        
        sortedPlayers.forEach((player, index) => {
            if (index === 0) {
                announcement += this.t('leading_fleet', { name: player.name, score: player.score.toString() });
            } else if (index === sortedPlayers.length - 1 && sortedPlayers.length > 2) {
                announcement += this.t('bringing_rear', { name: player.name, score: player.score.toString() });
            } else {
                announcement += this.t('follows_with', { name: player.name, score: player.score.toString() });
            }
        });

        announcement += this.t('may_winds_favor');
        return announcement;
    }

    // Safe translation helper
    private t(key: keyof Translation, params?: { [key: string]: string | number }): string {
        return translationSystem.translate(key, params);
    }

    // Public method for testing
    testCalculateRoundScore(bid: number, actual: number, bonus: number, roundNumber: number, playerCount?: number): number {
        // For testing, allow overriding player count
        if (playerCount !== undefined) {
            const cardsDealt = this.getCardsPerRound(roundNumber, playerCount);
            const scoringMode = this.getScoringMode();
            
            if (scoringMode === 'rascal') {
                // Rascal's scoring: potential points = 10 × cards dealt
                const potentialPoints = 10 * cardsDealt;
                const difference = Math.abs(bid - actual);
                
                if (difference === 0) {
                    // Direct hit: full points + bonus
                    return potentialPoints + bonus;
                } else if (difference === 1) {
                    // Glancing blow: half points + half bonus
                    return Math.floor(potentialPoints / 2) + Math.floor(bonus / 2);
                } else {
                    // Complete miss: no points
                    return 0;
                }
            } else {
                // Normal/Traditional Skull King scoring
                if (bid === 0) {
                    // Zero bid scoring: 10 points per card dealt for success
                    return actual === 0 ? 10 * cardsDealt + bonus : -10 * cardsDealt;
                } else {
                    // Non-zero bid scoring
                    if (bid === actual) {
                        // Correct prediction: 20 points per card dealt + bonus
                        return 20 * cardsDealt + bonus;
                    } else {
                        // Incorrect prediction: -10 points per difference (no bonus)
                        return -10 * Math.abs(bid - actual);
                    }
                }
            }
        }
        return this.calculateRoundScore(bid, actual, bonus, roundNumber);
    }
}

/**
 * SkullKingGame - Main game controller using MVVM architecture
 * Coordinates between ViewModel (business logic) and DOM (view)
 */
class SkullKingGame {
    private viewModel: GameViewModel;
    private deferredPrompt: BeforeInstallPromptEvent | null = null;

    constructor() {
        this.viewModel = new GameViewModel();
        this.init();
    }

    private init(): void {
        this.setupEventListeners();
        this.initializePWA();
        this.initializeTranslations();
        this.updateUI();
    }

    private setupEventListeners(): void {
        // Landing page
        const newGameBtn = document.getElementById('new-game-btn');
        newGameBtn?.addEventListener('click', () => this.handleNewGame());

        // Player names setup
        const addPlayerBtn = document.getElementById('add-player-btn');
        addPlayerBtn?.addEventListener('click', () => this.handleAddPlayer());

        const startGameBtn = document.getElementById('start-game-btn');
        startGameBtn?.addEventListener('click', () => this.handleStartGame());

        const closeSetupBtn = document.getElementById('close-setup-btn');
        closeSetupBtn?.addEventListener('click', () => this.showLanding());

        // In-game
        const newGameIngameBtn = document.getElementById('new-game-ingame-btn');
        newGameIngameBtn?.addEventListener('click', () => this.confirmNewGame());

        const addRoundBtn = document.getElementById('add-round-btn');
        addRoundBtn?.addEventListener('click', () => this.handleAddRound());

        const readScoresBtn = document.getElementById('read-scores-btn');
        readScoresBtn?.addEventListener('click', () => this.readScores());

        // Modal
        const modalConfirm = document.getElementById('modal-confirm');
        modalConfirm?.addEventListener('click', () => this.handleModalConfirm());

        const modalCancel = document.getElementById('modal-cancel');
        modalCancel?.addEventListener('click', () => this.hideModal());

        // Language selector
        const languageSelector = document.getElementById('language-selector') as HTMLSelectElement;
        languageSelector?.addEventListener('change', () => this.handleLanguageChange(languageSelector.value));
    }

    // Event Handlers
    private handleNewGame(): void {
        if (this.viewModel.isGameActive()) {
            this.confirmNewGame();
        } else {
            this.startPlayerSetup();
        }
    }

    private handleAddPlayer(): void {
        const tempPlayers = this.viewModel.getTempPlayers();
        if (tempPlayers.length >= 8) {
            this.showError(this.t('max_players_add_error'));
            return;
        }
        this.viewModel.addTempPlayer();
        this.updatePlayerInputs();
    }


    private handleStartGame(): void {
        // Get selected scoring mode
        const scoringModeInput = document.querySelector('input[name="scoring-mode"]:checked') as HTMLInputElement;
        if (scoringModeInput) {
            this.viewModel.setScoringMode(scoringModeInput.value as ScoringMode);
        }
        
        const error = this.viewModel.validateAndStartGame();
        if (error) {
            this.showError(error);
            return;
        }
        this.updateUI();
    }

    private handleAddRound(): void {
        const gameState = this.viewModel.getGameState();
        const roundData = this.collectRoundData(gameState.players);
        
        const error = this.viewModel.addRound(roundData);
        
        if (error) {
            this.showError(error);
            return;
        }

        this.updateUI();
        this.clearRoundInputs();
        this.showCommentary();
        
        // Scroll to the scores section after recording round
        const scoresSection = document.querySelector('.current-scores');
        if (scoresSection) {
            scoresSection.scrollIntoView({ behavior: 'smooth', block: 'start' });
        }
    }

    private handleModalConfirm(): void {
        this.viewModel.executeModalConfirm();
        this.hideModal();
    }

    // Helper Methods
    private startPlayerSetup(): void {
        this.viewModel.initializeTempPlayers();
        this.showPlayerSetup();
        this.updatePlayerInputs();
        
        // Restore scoring mode selection
        const scoringMode = this.viewModel.getScoringMode();
        const scoringModeInput = document.getElementById(`scoring-${scoringMode}`) as HTMLInputElement;
        if (scoringModeInput) {
            scoringModeInput.checked = true;
        }
    }

    private confirmNewGame(): void {
        this.showModal(
            this.t('new_game_modal_title'),
            this.t('new_game_modal_message')
        );
        
        this.viewModel.setModalConfirmCallback(() => {
            // Always keep names when user confirms new game
            this.viewModel.startNewGame(true);
            // Names are already preserved in startNewGame, no need to initialize
            this.showPlayerSetup();
            this.updatePlayerInputs();
            
            // Restore scoring mode selection
            const scoringMode = this.viewModel.getScoringMode();
            const scoringModeInput = document.getElementById(`scoring-${scoringMode}`) as HTMLInputElement;
            if (scoringModeInput) {
                scoringModeInput.checked = true;
            }
        });
    }

    // View Methods
    private updateUI(): void {
        const gameState = this.viewModel.getGameState();
        
        if (gameState.players.length === 0) {
            this.showLanding();
        } else {
            this.showGame();
            this.updateScoreDisplay(gameState.players);
            
            // Check if game is complete
            const isGameComplete = this.viewModel.isGameComplete();
            if (isGameComplete) {
                this.showWinnerAnnouncement();
                this.hideNewRoundInputs();
            } else {
                this.hideWinnerAnnouncement();
                this.showNewRoundInputs();
                this.updateRoundInputs(gameState.players, gameState.currentRound);
            }
            
            this.updatePreviousRounds(gameState.rounds);
            
            // Show commentary if we have rounds
            if (gameState.rounds.length > 0) {
                this.showCommentary();
            }
        }
    }

    private showLanding(): void {
        document.getElementById('landing-section')?.classList.remove('hidden');
        document.getElementById('player-names-section')?.classList.add('hidden');
        document.getElementById('game-section')?.classList.add('hidden');
        document.getElementById('new-game-section')?.classList.add('hidden');
    }

    private showPlayerSetup(): void {
        document.getElementById('landing-section')?.classList.add('hidden');
        document.getElementById('player-names-section')?.classList.remove('hidden');
        document.getElementById('game-section')?.classList.add('hidden');
        document.getElementById('new-game-section')?.classList.add('hidden');
        
        // Ensure scoring mode translations are applied
        this.updateAllTranslations();
    }

    private showGame(): void {
        document.getElementById('landing-section')?.classList.add('hidden');
        document.getElementById('player-names-section')?.classList.add('hidden');
        document.getElementById('game-section')?.classList.remove('hidden');
        document.getElementById('new-game-section')?.classList.remove('hidden');
    }

    private updatePlayerInputs(): void {
        const container = document.getElementById('player-names-inputs');
        const addPlayerBtn = document.getElementById('add-player-btn');
        if (!container) return;

        const tempPlayers = this.viewModel.getTempPlayers();
        container.innerHTML = tempPlayers.map((name, index) => `
            <div class="player-name-input">
                <input type="text" id="player-${index}" placeholder="${this.t('player_placeholder')}" value="${name}" onchange="game.updateTempPlayer(${index}, this.value)">
                <button class="btn-remove" onclick="game.removePlayer(${index})" title="Remove player">✕</button>
            </div>
        `).join('');

        // Hide/show Add Pirate button based on player count (max 8)
        if (addPlayerBtn) {
            if (tempPlayers.length >= 8) {
                addPlayerBtn.style.display = 'none';
            } else {
                addPlayerBtn.style.display = 'inline-block';
            }
        }
    }

    private updateScoreDisplay(players: Player[]): void {
        const scoreDisplay = document.getElementById('score-display');
        if (!scoreDisplay) return;

        // Get players sorted by score from the view model
        const sortedPlayers = this.viewModel.getPlayersSortedByScore();

        scoreDisplay.innerHTML = sortedPlayers.map(player => `
            <div class="player-score">
                <h4>${player.name}</h4>
                <div class="score-value">${player.score}</div>
            </div>
        `).join('');
    }

    private updateRoundInputs(players: Player[], currentRound: number): void {
        const container = document.getElementById('round-inputs');
        const roundNumberEl = document.getElementById('round-number');
        
        if (!container) return;
        
        const maxTricks = this.viewModel.getMaxTricksForCurrentRound();
        const roundDisplay = maxTricks < currentRound ? 
            `${currentRound} (${this.t('cards_each', { cards: maxTricks.toString() })})` : 
            currentRound.toString();
            
        if (roundNumberEl) {
            roundNumberEl.textContent = roundDisplay;
        }

        container.innerHTML = players.map((player, index) => `
            <div class="player-round-input">
                <h4>${player.name}</h4>
                <div class="round-input-row">
                    <div class="input-group">
                        <label for="bid-player-${index}" class="input-label">${this.t('bid_label')}</label>
                        <input type="number" id="bid-player-${index}" placeholder="0" min="0" max="${maxTricks}" oninput="game.updateRoundScoreByIndex(${index})">
                    </div>
                    <div class="input-group">
                        <label for="actual-player-${index}" class="input-label">${this.t('won_label')}</label>
                        <input type="number" id="actual-player-${index}" placeholder="0" min="0" max="${maxTricks}" oninput="game.updateRoundScoreByIndex(${index})">
                    </div>
                    <div class="input-group">
                        <label for="bonus-player-${index}" class="input-label">${this.t('bonus_label')}</label>
                        <input type="number" id="bonus-player-${index}" placeholder="0" min="0" oninput="game.updateRoundScoreByIndex(${index})">
                    </div>
                    <div class="input-group">
                        <label class="input-label">${this.t('score_label')}</label>
                        <div id="score-player-${index}" class="computed-score">-</div>
                    </div>
                </div>
            </div>
        `).join('');
        
        // Initialize computed scores for all players
        players.forEach((player, index) => this.updateRoundScoreInternalByIndex(index));
    }

    private updatePreviousRounds(rounds: RoundData[]): void {
        const container = document.getElementById('previous-rounds');
        if (!container) return;

        if (rounds.length === 0) {
            container.innerHTML = '';
            return;
        }

        // Display rounds in reverse order (newest first)
        const sortedRounds = [...rounds].reverse();
        
        container.innerHTML = sortedRounds.map((round, index) => `
            <div class="round-display parchment">
                <div class="round-header">
                    <h3>${this.t('round_display', { round: round.roundNumber.toString() })}</h3>
                    ${index === 0 ? `<button class="btn btn-secondary" onclick="game.handleUpdateLastRound()">${this.t('edit_round_button')}</button>` : ''}
                </div>
                <div class="round-data">
                    <div class="round-data-header">
                        <span>${this.t('player_label')}</span>
                        <span>${this.t('bid_label')}</span>
                        <span>${this.t('won_label')}</span>
                        <span>${this.t('bonus_label')}</span>
                        <span>${this.t('score_label')}</span>
                    </div>
                    ${round.playerData.map(data => `
                        <div class="player-round-data">
                            <strong>${data.playerName}</strong>
                            <span>${data.bid}</span>
                            <span>${data.actual}</span>
                            <span>${data.bonus}</span>
                            <span>${data.roundScore > 0 ? '+' : ''}${data.roundScore}</span>
                        </div>
                    `).join('')}
                </div>
            </div>
        `).join('');
    }

    private collectRoundData(players: Player[]): { [playerName: string]: { bid: number; actual: number; bonus: number } } {
        const data: { [playerName: string]: { bid: number; actual: number; bonus: number } } = {};

        players.forEach((player, index) => {
            const bidInput = document.getElementById(`bid-player-${index}`) as HTMLInputElement;
            const actualInput = document.getElementById(`actual-player-${index}`) as HTMLInputElement;
            const bonusInput = document.getElementById(`bonus-player-${index}`) as HTMLInputElement;

            // Parse values, defaulting to 0 for empty inputs
            const bidValue = bidInput?.value?.trim() || '0';
            const actualValue = actualInput?.value?.trim() || '0';
            const bonusValue = bonusInput?.value?.trim() || '0';

            data[player.name] = {
                bid: parseInt(bidValue),
                actual: parseInt(actualValue),
                bonus: parseInt(bonusValue)
            };
        });

        return data;
    }

    private clearRoundInputs(): void {
        const inputs = document.querySelectorAll('#round-inputs input') as NodeListOf<HTMLInputElement>;
        inputs.forEach(input => input.value = '');
    }

    private showCommentary(): void {
        const commentary = this.viewModel.getCurrentCommentary();
        const commentaryEl = document.getElementById('pirate-commentary');
        const textEl = document.getElementById('commentary-text');

        if (commentaryEl && textEl) {
            if (commentary) {
                textEl.textContent = commentary;
                commentaryEl.classList.remove('hidden');
            } else {
                commentaryEl.classList.add('hidden');
            }
        }
    }
    
    private showWinnerAnnouncement(): void {
        const winnerAnnouncement = document.getElementById('winner-announcement');
        const winnerText = document.getElementById('winner-text');
        if (winnerAnnouncement && winnerText) {
            const announcement = this.viewModel.generateWinnerAnnouncement();
            winnerText.textContent = announcement;
            winnerAnnouncement.classList.remove('hidden');
        }
    }
    
    private hideWinnerAnnouncement(): void {
        const winnerAnnouncement = document.getElementById('winner-announcement');
        if (winnerAnnouncement) {
            winnerAnnouncement.classList.add('hidden');
        }
    }
    
    private showNewRoundInputs(): void {
        const newRoundEl = document.getElementById('new-round');
        if (newRoundEl) {
            newRoundEl.classList.remove('hidden');
        }
    }
    
    private hideNewRoundInputs(): void {
        const newRoundEl = document.getElementById('new-round');
        if (newRoundEl) {
            newRoundEl.classList.add('hidden');
        }
    }


    private showModal(title: string, message: string): void {
        const modal = document.getElementById('modal');
        const titleEl = document.getElementById('modal-title');
        const messageEl = document.getElementById('modal-message');
        const modalButtons = document.getElementById('modal-buttons');

        if (!modal || !titleEl || !messageEl) return;

        titleEl.textContent = title;
        messageEl.textContent = message;
        
        // Show standard buttons
        modalButtons?.classList.remove('hidden');

        modal.classList.remove('hidden');
    }

    private showErrorModal(message: string): void {
        const modal = document.getElementById('modal');
        const titleEl = document.getElementById('modal-title');
        const messageEl = document.getElementById('modal-message');
        const modalButtons = document.getElementById('modal-buttons');
        const modalConfirm = document.getElementById('modal-confirm');
        const modalCancel = document.getElementById('modal-cancel');

        if (!modal || !titleEl || !messageEl) return;

        titleEl.textContent = this.t('input_error_title');
        messageEl.textContent = message;

        modalButtons?.classList.remove('hidden');

        // Show only the confirm button (OK)
        if (modalConfirm && modalCancel) {
            modalConfirm.textContent = this.t('fix_it_button');
            modalCancel.style.display = 'none';
        }

        // Clear any existing callback and set error modal behavior
        this.viewModel.setModalConfirmCallback(() => {
            if (modalCancel) modalCancel.style.display = 'inline-block';
            if (modalConfirm) modalConfirm.textContent = this.t('aye_button');
        });

        modal.classList.remove('hidden');
    }

    private hideModal(): void {
        const modal = document.getElementById('modal');
        modal?.classList.add('hidden');
    }


    private showError(message: string): void {
        this.showErrorModal(message);
    }

    private getLanguageSpecificSpeechSettings(language: string): { rate: number; pitch: number; volume: number } {
        // Language-specific speech settings for authentic pirate voices
        interface SpeechSettings {
            rate: number;
            pitch: number;
            volume: number;
        }
        
        const settings: { [key: string]: SpeechSettings } = {
            'en': {
                rate: 0.7,   // Slower and more dramatic for English
                pitch: 0.7,  // Lower pitch for gruff pirate voice
                volume: 1.0
            },
            'de': {
                rate: 0.65,  // Slightly slower for German to sound more commanding
                pitch: 0.6,  // Even lower pitch for authoritative German pirate
                volume: 1.0
            },
            'es': {
                rate: 0.75,  // Slightly faster for Spanish passion
                pitch: 0.75, // Slightly higher pitch for Spanish expressiveness
                volume: 1.0
            }
        };

        return settings[language] || settings['en'];
    }

    private readScores(): void {
        // Check if browser supports speech synthesis
        if (!('speechSynthesis' in window) || !('SpeechSynthesisUtterance' in window)) {
            this.showErrorModal(this.t('browser_speech_error'));
            return;
        }

        // Cancel any ongoing speech
        window.speechSynthesis.cancel();

        // Force refresh the view model's translation context before creating announcement
        const announcement = this.viewModel.createScoreAnnouncement();

        // Create and configure the utterance for maximum pirate effect
        const utterance = new SpeechSynthesisUtterance(announcement);
        
        // Get current language
        const currentLang = translationSystem.getCurrentLanguage();
        
        // Set the utterance language based on current selection
        utterance.lang = currentLang === 'de' ? 'de-DE' : 
                        currentLang === 'es' ? 'es-ES' : 'en-US';
        
        // Set language-specific speech parameters for pirate effect
        const speechSettings = this.getLanguageSpecificSpeechSettings(currentLang);
        utterance.rate = speechSettings.rate;
        utterance.pitch = speechSettings.pitch;
        utterance.volume = speechSettings.volume;

        // Function to set language-appropriate voice
        const setLanguageVoice = () => {
            const voices = window.speechSynthesis.getVoices();
            
            if (voices.length === 0) {
                // Voices not loaded yet, try again in a moment
                setTimeout(setLanguageVoice, 100);
                return;
            }

            let pirateVoice = null;

            // Define language preferences for voice selection
            interface VoicePreference {
                langCodes: string[];
                preferredNames: string[];
            }
            
            const voicePreferences: { [key: string]: VoicePreference } = {
                'en': {
                    langCodes: ['en-US', 'en-GB', 'en-AU', 'en'],
                    preferredNames: ['daniel', 'david', 'alex', 'male', 'aaron', 'fred']
                },
                'de': {
                    langCodes: ['de-DE', 'de-AT', 'de-CH', 'de'],
                    preferredNames: ['male', 'markus', 'stefan', 'hans', 'dieter']
                },
                'es': {
                    langCodes: ['es-ES', 'es-MX', 'es-AR', 'es-US', 'es'],
                    preferredNames: ['male', 'carlos', 'diego', 'jorge', 'manuel', 'pablo']
                }
            };

            const prefs = voicePreferences[currentLang] || voicePreferences['en'];

            // Try to find the best voice for the current language
            for (const langCode of prefs.langCodes) {
                // First, try to find preferred male voices
                for (const preferredName of prefs.preferredNames) {
                    pirateVoice = voices.find(voice => 
                        voice.lang.toLowerCase().startsWith(langCode.toLowerCase()) &&
                        voice.name.toLowerCase().includes(preferredName.toLowerCase())
                    );
                    if (pirateVoice) break;
                }
                if (pirateVoice) break;

                // If no preferred voice found, try any male voice for this language
                pirateVoice = voices.find(voice => 
                    voice.lang.toLowerCase().startsWith(langCode.toLowerCase()) &&
                    !voice.name.toLowerCase().includes('female')
                );
                if (pirateVoice) break;

                // If still no voice, try any voice for this language
                pirateVoice = voices.find(voice => 
                    voice.lang.toLowerCase().startsWith(langCode.toLowerCase())
                );
                if (pirateVoice) break;
            }

            // Fallback to any English voice if no voice found for selected language
            if (!pirateVoice) {
                pirateVoice = voices.find(voice => 
                    voice.lang.startsWith('en') && 
                    !voice.name.toLowerCase().includes('female')
                ) || voices.find(voice => voice.lang.startsWith('en'));
            }

            if (pirateVoice) {
                utterance.voice = pirateVoice;
                utterance.lang = pirateVoice.lang; // Set the language explicitly
                console.log(`🗣️ Using voice: ${pirateVoice.name} (${pirateVoice.lang}) for language: ${currentLang}`);
            } else {
                console.warn(`⚠️ No suitable voice found for language: ${currentLang}`);
            }

            // Speak!
            window.speechSynthesis.speak(utterance);
        };

        // Set voice and speak
        setLanguageVoice();
    }

    private updateRoundScoreInternal(playerName: string): void {
        const bidInput = document.getElementById(`bid-${playerName}`) as HTMLInputElement;
        const actualInput = document.getElementById(`actual-${playerName}`) as HTMLInputElement;
        const bonusInput = document.getElementById(`bonus-${playerName}`) as HTMLInputElement;
        const scoreDisplay = document.getElementById(`score-${playerName}`);
        
        if (!bidInput || !actualInput || !bonusInput || !scoreDisplay) return;
        
        // Get input values
        const bidValue = bidInput.value.trim();
        const actualValue = actualInput.value.trim();
        const bonusValue = bonusInput.value.trim();
        
        // Only show score when both bid and actual have values (Option 1: Progressive Disclosure)
        if (!bidValue || !actualValue) {
            scoreDisplay.textContent = '-';
            scoreDisplay.className = 'computed-score';
            return;
        }
        
        // Parse values (bonus defaults to 0 if empty)
        const bid = parseInt(bidValue);
        const actual = parseInt(actualValue);
        const bonus = bonusValue ? parseInt(bonusValue) : 0;
        
        // Use the centralized validation
        const validationError = this.viewModel.validateSinglePlayerInput(bid, actual, bonus, playerName);
        if (validationError) {
            scoreDisplay.textContent = '-';
            scoreDisplay.className = 'computed-score invalid';
            return;
        }
        
        // Calculate score
        const currentRound = this.viewModel.getCurrentRoundNumber();
        const score = this.viewModel.testCalculateRoundScore(bid, actual, bonus, currentRound);
        
        // Display score with appropriate styling
        scoreDisplay.textContent = score > 0 ? `+${score}` : score.toString();
        scoreDisplay.className = `computed-score ${score > 0 ? 'positive' : score < 0 ? 'negative' : 'zero'}`;
    }

    private updateRoundScoreInternalByIndex(playerIndex: number): void {
        const bidInput = document.getElementById(`bid-player-${playerIndex}`) as HTMLInputElement;
        const actualInput = document.getElementById(`actual-player-${playerIndex}`) as HTMLInputElement;
        const bonusInput = document.getElementById(`bonus-player-${playerIndex}`) as HTMLInputElement;
        const scoreDisplay = document.getElementById(`score-player-${playerIndex}`);
        
        if (!bidInput || !actualInput || !bonusInput || !scoreDisplay) return;
        
        // Get input values
        const bidValue = bidInput.value.trim();
        const actualValue = actualInput.value.trim();
        const bonusValue = bonusInput.value.trim();
        
        // Only show score when both bid and actual have values (Option 1: Progressive Disclosure)
        if (!bidValue || !actualValue) {
            scoreDisplay.textContent = '-';
            scoreDisplay.className = 'computed-score';
            return;
        }
        
        // Parse values (bonus defaults to 0 if empty)
        const bid = parseInt(bidValue);
        const actual = parseInt(actualValue);
        const bonus = bonusValue ? parseInt(bonusValue) : 0;
        
        // Get player name for validation
        const players = this.viewModel.getPlayers();
        const playerName = players[playerIndex]?.name || '';
        
        // Use the centralized validation
        const validationError = this.viewModel.validateSinglePlayerInput(bid, actual, bonus, playerName);
        if (validationError) {
            scoreDisplay.textContent = '-';
            scoreDisplay.className = 'computed-score invalid';
            return;
        }
        
        // Calculate score
        const currentRound = this.viewModel.getCurrentRoundNumber();
        const score = this.viewModel.testCalculateRoundScore(bid, actual, bonus, currentRound);
        
        // Display score with appropriate styling
        scoreDisplay.textContent = score > 0 ? `+${score}` : score.toString();
        scoreDisplay.className = `computed-score ${score > 0 ? 'positive' : score < 0 ? 'negative' : 'zero'}`;
    }

    // Public API for HTML event handlers
    public updateTempPlayer(index: number, value: string): void {
        this.viewModel.updateTempPlayer(index, value);
    }

    public removePlayer(index: number): void {
        this.viewModel.removeTempPlayer(index);
        this.updatePlayerInputs();
    }

    public updateRoundScore(playerName: string): void {
        this.updateRoundScoreInternal(playerName);
    }

    public updateRoundScoreByIndex(playerIndex: number): void {
        const players = this.viewModel.getPlayers();
        if (playerIndex >= 0 && playerIndex < players.length) {
            this.updateRoundScoreInternalByIndex(playerIndex);
        }
    }

    public handleUpdateLastRound(): void {
        // Remove the last round and get its data for pre-filling
        const lastRoundData = this.viewModel.removeLastRound();
        if (!lastRoundData) {
            this.showError(this.t('no_rounds_to_edit_error'));
            return;
        }

        // Ensure the round inputs are visible for editing, even if game was complete
        this.showNewRoundInputs();
        
        // Update UI to reflect the new game state (with last round removed)
        this.updateUI();

        // Populate the inputs with the removed round's data for editing
        const players = this.viewModel.getPlayers();
        for (const [playerName, data] of Object.entries(lastRoundData)) {
            // Find player index by name
            const playerIndex = players.findIndex((p: Player) => p.name === playerName);
            if (playerIndex === -1) continue;
            
            const bidInput = document.getElementById(`bid-player-${playerIndex}`) as HTMLInputElement;
            const actualInput = document.getElementById(`actual-player-${playerIndex}`) as HTMLInputElement;
            const bonusInput = document.getElementById(`bonus-player-${playerIndex}`) as HTMLInputElement;

            if (bidInput) bidInput.value = data.bid.toString();
            if (actualInput) actualInput.value = data.actual.toString();
            if (bonusInput) bonusInput.value = data.bonus.toString();
            
            // Update the computed score for this player
            this.updateRoundScoreInternalByIndex(playerIndex);
        }
        
        // Scroll to the round inputs section for editing
        const roundInputsSection = document.getElementById('new-round');
        if (roundInputsSection) {
            roundInputsSection.scrollIntoView({ behavior: 'smooth', block: 'start' });
        }
    }

    // Translation Management
    private initializeTranslations(): void {
        // Set initial language in selector
        const languageSelector = document.getElementById('language-selector') as HTMLSelectElement;
        if (languageSelector) {
            languageSelector.value = translationSystem.getCurrentLanguage();
        }

        // Listen for language change events
        window.addEventListener('languageChanged', () => {
            this.updateAllTranslations();
        });

        // Initial translation update
        this.updateAllTranslations();
    }

    private handleLanguageChange(language: string): void {
        translationSystem.setLanguage(language);
    }
    
    // Safe translation helper
    private t(key: keyof Translation, params?: { [key: string]: string | number }): string {
        return translationSystem.translate(key, params);
    }

    private updateAllTranslations(): void {
        // Update meta tags
        this.updateMetaTags();
        
        // Update static content
        this.updateStaticContent();
        
        // Update dynamic content if game is active
        if (this.viewModel.isGameActive()) {
            // Update all round commentaries to current language
            this.viewModel.updateAllCommentariesToCurrentLanguage();
            this.updateUI();
            // Force refresh commentary with new language
            this.showCommentary();
        }
    }

    private updateMetaTags(): void {
        // Update document title
        const title = document.getElementById('page-title') as HTMLTitleElement;
        if (title) title.textContent = this.t('page_title');

        // Update meta description
        const description = document.querySelector('meta[name="description"]') as HTMLMetaElement;
        if (description) description.content = this.t('page_description');

        // Update meta keywords
        const keywords = document.querySelector('meta[name="keywords"]') as HTMLMetaElement;
        if (keywords) keywords.content = this.t('page_keywords');

        // Update Open Graph tags
        const ogTitle = document.querySelector('meta[property="og:title"]') as HTMLMetaElement;
        if (ogTitle) ogTitle.content = this.t('og_title');

        const ogDescription = document.querySelector('meta[property="og:description"]') as HTMLMetaElement;
        if (ogDescription) ogDescription.content = this.t('og_description');

        // Update Twitter tags
        const twitterTitle = document.querySelector('meta[name="twitter:title"]') as HTMLMetaElement;
        if (twitterTitle) twitterTitle.content = this.t('og_title');

        const twitterDescription = document.querySelector('meta[name="twitter:description"]') as HTMLMetaElement;
        if (twitterDescription) twitterDescription.content = this.t('twitter_description');

        // Update app title
        const appTitle = document.querySelector('meta[name="apple-mobile-web-app-title"]') as HTMLMetaElement;
        if (appTitle) appTitle.content = this.t('app_title');
    }

    private updateStaticContent(): void {
        // Header
        const headerTitle = document.getElementById('header-title');
        if (headerTitle) headerTitle.textContent = this.t('header_title');

        const headerTagline = document.getElementById('header-tagline');
        if (headerTagline) headerTagline.textContent = this.t('header_tagline');

        // Landing page
        const landingTitle = document.getElementById('landing-title');
        if (landingTitle) landingTitle.textContent = this.t('landing_title');

        const landingDescription = document.getElementById('landing-description');
        if (landingDescription) landingDescription.textContent = this.t('landing_description');

        const landingSubtitle = document.getElementById('landing-subtitle');
        if (landingSubtitle) landingSubtitle.textContent = this.t('landing_subtitle');

        // Features
        const featureMobile = document.getElementById('feature-mobile');
        if (featureMobile) featureMobile.innerHTML = this.t('feature_mobile');

        const featureCalculator = document.getElementById('feature-calculator');
        if (featureCalculator) featureCalculator.innerHTML = this.t('feature_calculator');

        const featureCommentary = document.getElementById('feature-commentary');
        if (featureCommentary) featureCommentary.innerHTML = this.t('feature_commentary');

        const featureAudio = document.getElementById('feature-audio');
        if (featureAudio) featureAudio.innerHTML = this.t('feature_audio');

        const featureSaving = document.getElementById('feature-saving');
        if (featureSaving) featureSaving.innerHTML = this.t('feature_saving');

        const whyChooseTitle = document.getElementById('why-choose-title');
        if (whyChooseTitle) whyChooseTitle.textContent = this.t('why_choose_title');

        const whyChooseDescription = document.getElementById('why-choose-description');
        if (whyChooseDescription) whyChooseDescription.textContent = this.t('why_choose_description');

        // Buttons
        const newGameBtn = document.getElementById('new-game-btn');
        if (newGameBtn) newGameBtn.textContent = this.t('start_button');

        const nameCrewTitle = document.getElementById('name-crew-title');
        if (nameCrewTitle) nameCrewTitle.textContent = this.t('name_crew_title');

        const addPlayerBtn = document.getElementById('add-player-btn');
        if (addPlayerBtn) addPlayerBtn.textContent = this.t('add_pirate_button');

        const startGameBtn = document.getElementById('start-game-btn');
        if (startGameBtn) startGameBtn.textContent = this.t('set_sail_button');

        // Scoring mode translations
        const scoringModeLabel = document.getElementById('scoring-mode-label');
        if (scoringModeLabel) scoringModeLabel.textContent = this.t('scoring_mode_label');

        const scoringModeNormal = document.getElementById('scoring-mode-normal');
        if (scoringModeNormal) scoringModeNormal.textContent = this.t('scoring_mode_normal');

        const scoringModeNormalDesc = document.getElementById('scoring-mode-normal-desc');
        if (scoringModeNormalDesc) scoringModeNormalDesc.textContent = this.t('scoring_mode_normal_desc');

        const scoringModeRascal = document.getElementById('scoring-mode-rascal');
        if (scoringModeRascal) scoringModeRascal.textContent = this.t('scoring_mode_rascal');

        const scoringModeRascalDesc = document.getElementById('scoring-mode-rascal-desc');
        if (scoringModeRascalDesc) scoringModeRascalDesc.textContent = this.t('scoring_mode_rascal_desc');

        const newGameIngameBtn = document.getElementById('new-game-ingame-btn');
        if (newGameIngameBtn) newGameIngameBtn.textContent = this.t('new_game_button');

        // Game section
        const currentBountyTitle = document.getElementById('current-bounty-title');
        if (currentBountyTitle) currentBountyTitle.textContent = this.t('current_bounty_title');

        const readScoresBtn = document.getElementById('read-scores-btn');
        if (readScoresBtn) readScoresBtn.innerHTML = `🔊 ${this.t('read_scores_button').replace('🔊 ', '')}`;

        const gameCompleteTitle = document.getElementById('game-complete-title');
        if (gameCompleteTitle) gameCompleteTitle.textContent = this.t('game_complete_title');

        const roundLabel = document.getElementById('round-label');
        if (roundLabel) roundLabel.textContent = this.t('round_label');

        const addRoundBtn = document.getElementById('add-round-btn');
        if (addRoundBtn) addRoundBtn.textContent = this.t('record_round_button');

        // Modal
        const modalTitle = document.getElementById('modal-title');
        if (modalTitle) modalTitle.textContent = this.t('confirm_action_title');

        const keepNamesLabel = document.getElementById('keep-names-label');
        if (keepNamesLabel) keepNamesLabel.textContent = this.t('keep_names_label');

        const newPlayersBtn = document.getElementById('new-players-btn');
        if (newPlayersBtn) newPlayersBtn.textContent = this.t('new_players_button');

        const cancelNewGameBtn = document.getElementById('cancel-new-game-btn');
        if (cancelNewGameBtn) cancelNewGameBtn.textContent = this.t('cancel_button');

        const modalConfirm = document.getElementById('modal-confirm');
        if (modalConfirm) modalConfirm.textContent = this.t('aye_button');

        const modalCancel = document.getElementById('modal-cancel');
        if (modalCancel) modalCancel.textContent = this.t('nay_button');

        // Footer
        const disclaimerTitle = document.getElementById('disclaimer-title');
        if (disclaimerTitle) disclaimerTitle.textContent = this.t('disclaimer_title');

        const disclaimerText1 = document.getElementById('disclaimer-text-1');
        if (disclaimerText1) disclaimerText1.textContent = this.t('disclaimer_text_1');

        const disclaimerText2 = document.getElementById('disclaimer-text-2');
        if (disclaimerText2) disclaimerText2.textContent = this.t('disclaimer_text_2');

        const feedbackText = document.getElementById('feedback-text');
        if (feedbackText) feedbackText.textContent = this.t('feedback_text');
    }

    // PWA Install Functionality
    private initializePWA(): void {
        // Guard for test environment
        if (typeof document === 'undefined') return;
        
        // Register service worker
        if ('serviceWorker' in navigator) {
            window.addEventListener('load', () => {
                navigator.serviceWorker.register('./sw.js')
                    .then(registration => {
                        console.log('Service Worker registered:', registration);
                    })
                    .catch(error => {
                        console.log('Service Worker registration failed:', error);
                    });
            });
        }
        
        // Don't show install buttons if already in standalone mode (installed)
        if ((window.matchMedia && window.matchMedia('(display-mode: standalone)').matches) || 
            (window.navigator as any).standalone) {
            this.hideInstallButtons();
            return;
        }
        
        // Add event listeners to existing install buttons
        this.setupInstallButtons();
    }

    private setupInstallButtons(): void {
        // Add event listener to the header install button
        const installBtnHeader = document.getElementById('install-app-btn-header');
        
        if (installBtnHeader) {
            installBtnHeader.addEventListener('click', () => this.showInstallInstructions());
        }
    }

    private hideInstallButtons(): void {
        const installBtnHeader = document.getElementById('install-app-btn-header');
        
        if (installBtnHeader) {
            installBtnHeader.style.display = 'none';
        }
    }

    private showInstallInstructions(): void {
        // Show instructions for manual installation
        let modal = document.getElementById('install-instructions-modal');
        if (!modal) {
            modal = document.createElement('div');
            modal.id = 'install-instructions-modal';
            modal.className = 'install-modal';
            modal.innerHTML = `
                <div class="install-modal-content">
                    <h3>${this.t('add_to_home_title')}</h3>
                    <div class="install-instructions">
                        <p><strong>${this.t('android_chrome_title')}</strong></p>
                        <ol>
                            <li>${this.t('android_step_1')}</li>
                            <li>${this.t('android_step_2')}</li>
                            <li>${this.t('android_step_3')}</li>
                        </ol>
                        <p><strong>${this.t('ios_safari_title')}</strong></p>
                        <ol>
                            <li>${this.t('ios_step_1')}</li>
                            <li>${this.t('ios_step_2')}</li>
                            <li>${this.t('ios_step_3')}</li>
                        </ol>
                    </div>
                    <button class="install-modal-close" onclick="this.parentElement.parentElement.style.display='none'">${this.t('close_button')}</button>
                </div>
            `;
            document.body.appendChild(modal);
        }
        modal.style.display = 'flex';
    }

    // Public method for testing the scoring logic
    public testCalculateRoundScore(bid: number, actual: number, bonus: number, roundNumber: number, playerCount?: number): number {
        return this.viewModel.testCalculateRoundScore(bid, actual, bonus, roundNumber, playerCount);
    }
    
    // Public method for validation testing
    public testValidateSinglePlayerInput(bid: number, actual: number, bonus: number, playerName: string, roundNumber?: number): string | null {
        return this.viewModel.validateSinglePlayerInput(bid, actual, bonus, playerName, roundNumber);
    }
    
    // Public method for testing scoring modes
    public getViewModel(): GameViewModel {
        return this.viewModel;
    }
}

// Initialize game
const game = new SkullKingGame();

// Expose game instance and class globally
(window as any).game = game;
(window as any).SkullKingGame = SkullKingGame;